---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8081}]
  customize:
    memory: 1536
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: './test/integration/default/data_bags'
    encrypted_data_bag_secret_key_path: './test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[wiw-blog::default]
    attributes:
